import Head from 'next/head';
import React from "react";
import { Navbar } from '../components/subComponents/Navbar';
import { Main } from '../components/sections/Main';
import { Inter } from '@next/font/google';
import { About } from '../components/sections/About';
import Sections from '../components/sections/Sections';
import { Experience } from "../components/sections/Experience";


const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Larissa | FullStack </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Experience />
    </div>
  );
}
